name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    #Download Python for pre-commit
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
          python-version: '3.11'
    #Install build tools and clang
    - name: Install build tools
      run:
          sudo apt-get update
          sudo apt-get install -y build-essential clang clang-format
    #Install pre-commit
    - name: Install pre-commit
      run:
          python -m pip install --upgrade pip
          pip install pre-commit
    #Run pre-commit
    - name: Run pre-commit hooks
      run: pre-commit run --all-files
    - name: Build project
      run: make
    - name: Run tests
      run: make test
